{
  "name": "FabricCompliance",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [

      {
        "name": "violations",
        "columns": [
          { "name": "triplet_name",    "dataType": "string",   "sourceColumn": "triplet_name"    },
          { "name": "workspace",       "dataType": "string",   "sourceColumn": "workspace"       },
          { "name": "object_type",     "dataType": "string",   "sourceColumn": "object_type"     },
          { "name": "object_name",     "dataType": "string",   "sourceColumn": "object_name"     },
          { "name": "violation_type",  "dataType": "string",   "sourceColumn": "violation_type"  },
          { "name": "sync_state",      "dataType": "string",   "sourceColumn": "sync_state"      },
          { "name": "detected_at",     "dataType": "dateTime", "sourceColumn": "detected_at",
            "formatString": "Short Date" }
        ],
        "partitions": [
          {
            "name": "violations-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Parquet.Document(File.Contents(\"violations.parquet\"))",
                "in",
                "    Source"
              ]
            }
          }
        ]
      },

      {
        "name": "inventory",
        "columns": [
          { "name": "triplet_name",    "dataType": "string",   "sourceColumn": "triplet_name"   },
          { "name": "workspace",       "dataType": "string",   "sourceColumn": "workspace"      },
          { "name": "object_type",     "dataType": "string",   "sourceColumn": "object_type"    },
          { "name": "object_name",     "dataType": "string",   "sourceColumn": "object_name"    },
          { "name": "sync_state",      "dataType": "string",   "sourceColumn": "sync_state"     },
          { "name": "exists_in_dev",   "dataType": "boolean",  "sourceColumn": "exists_in_dev",
            "formatString": "\"✓\";\"✓\";\"✗\"" },
          { "name": "exists_in_test",  "dataType": "boolean",  "sourceColumn": "exists_in_test",
            "formatString": "\"✓\";\"✓\";\"✗\"" },
          { "name": "exists_in_prod",  "dataType": "boolean",  "sourceColumn": "exists_in_prod",
            "formatString": "\"✓\";\"✓\";\"✗\"" },
          { "name": "exists_in_git",   "dataType": "boolean",  "sourceColumn": "exists_in_git",
            "formatString": "\"✓\";\"✓\";\"✗\"" },
          { "name": "last_modified",   "dataType": "dateTime", "sourceColumn": "last_modified",
            "formatString": "Short Date" },
          {
            "name": "has_violation",
            "dataType": "string",
            "type": "calculated",
            "expression": "IF(CALCULATE(COUNTROWS(violations), violations[object_name] = inventory[object_name] && violations[triplet_name] = inventory[triplet_name]) > 0, \"Yes\", \"No\")"
          }
        ],
        "partitions": [
          {
            "name": "inventory-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Parquet.Document(File.Contents(\"inventory.parquet\"))",
                "in",
                "    Source"
              ]
            }
          }
        ]
      },

      {
        "name": "Measures",
        "columns": [
          {
            "name": "_placeholder",
            "dataType": "int64",
            "isHidden": true,
            "type": "calculated",
            "expression": "0"
          }
        ],
        "partitions": [
          {
            "name": "Measures-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let Source = #table({\"_placeholder\"}, {{0}}) in Source"
            }
          }
        ],
        "measures": [

          {
            "name": "Total Violations",
            "expression": "COUNTROWS(violations)",
            "formatString": "#,0",
            "displayFolder": "Summary"
          },

          {
            "name": "Total Objects",
            "expression": "COUNTROWS(inventory)",
            "formatString": "#,0",
            "displayFolder": "Summary"
          },

          {
            "name": "Objects In Dev",
            "expression": "CALCULATE(COUNTROWS(inventory), inventory[exists_in_dev] = TRUE())",
            "formatString": "#,0",
            "displayFolder": "Summary"
          },

          {
            "name": "Git Backed Count",
            "expression": "CALCULATE(COUNTROWS(inventory), inventory[exists_in_git] = TRUE())",
            "formatString": "#,0",
            "displayFolder": "Summary"
          },

          {
            "name": "Fully Synced Count",
            "expression": [
              "CALCULATE(",
              "    COUNTROWS(inventory),",
              "    inventory[sync_state] = \"Synced\",",
              "    inventory[exists_in_dev] = TRUE(),",
              "    inventory[exists_in_test] = TRUE(),",
              "    inventory[exists_in_prod] = TRUE()",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Summary"
          },

          {
            "name": "Critical Orphans",
            "expression": [
              "CALCULATE(",
              "    COUNTROWS(violations),",
              "    violations[violation_type] = \"ORPHANED_OBJECT\",",
              "    violations[workspace] IN {\"Test\", \"Prod\"}",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Summary"
          },

          {
            "name": "Compliance Rate",
            "expression": [
              "VAR _total = [Total Objects]",
              "VAR _violations = [Total Violations]",
              "RETURN",
              "IF(",
              "    _total = 0, BLANK(),",
              "    DIVIDE(_total - _violations, _total) * 100",
              ")"
            ],
            "formatString": "0.0\"%\"",
            "displayFolder": "Summary"
          },

          {
            "name": "Workspace Compliance Rate",
            "expression": [
              "VAR _wsTotal = COUNTROWS(inventory)",
              "VAR _wsViolations = CALCULATE(",
              "    COUNTROWS(violations),",
              "    TREATAS(VALUES(inventory[workspace]), violations[workspace])",
              ")",
              "RETURN",
              "IF(",
              "    _wsTotal = 0, BLANK(),",
              "    DIVIDE(_wsTotal - _wsViolations, _wsTotal) * 100",
              ")"
            ],
            "formatString": "0.0\"%\"",
            "displayFolder": "Workspace"
          },

          {
            "name": "Top Violation Type",
            "expression": [
              "CALCULATE(",
              "    FIRSTNONBLANK(violations[violation_type], 1),",
              "    TOPN(1,",
              "        SUMMARIZE(violations, violations[violation_type], \"_cnt\", COUNTROWS(violations)),",
              "        [_cnt], DESC",
              "    )",
              ")"
            ],
            "displayFolder": "Summary"
          },

          {
            "name": "Exists In Dev",
            "expression": [
              "VAR _name = SELECTEDVALUE(violations[object_name])",
              "VAR _trip = SELECTEDVALUE(violations[triplet_name])",
              "RETURN",
              "IF(",
              "    CALCULATE(",
              "        COUNTROWS(inventory),",
              "        inventory[object_name] = _name,",
              "        inventory[triplet_name] = _trip,",
              "        inventory[exists_in_dev] = TRUE()",
              "    ) > 0,",
              "    \"✓\", \"✗\"",
              ")"
            ],
            "displayFolder": "Violations"
          },

          {
            "name": "Exists In Git",
            "expression": [
              "VAR _name = SELECTEDVALUE(violations[object_name])",
              "VAR _trip = SELECTEDVALUE(violations[triplet_name])",
              "RETURN",
              "IF(",
              "    CALCULATE(",
              "        COUNTROWS(inventory),",
              "        inventory[object_name] = _name,",
              "        inventory[triplet_name] = _trip,",
              "        inventory[exists_in_git] = TRUE()",
              "    ) > 0,",
              "    \"✓\", \"✗\"",
              ")"
            ],
            "displayFolder": "Violations"
          },

          {
            "name": "Violation Flag",
            "expression": [
              "VAR _name = SELECTEDVALUE(inventory[object_name])",
              "VAR _trip = SELECTEDVALUE(inventory[triplet_name])",
              "VAR _vcount = CALCULATE(",
              "    COUNTROWS(violations),",
              "    violations[object_name] = _name,",
              "    violations[triplet_name] = _trip",
              ")",
              "RETURN",
              "IF(_vcount > 0,",
              "    CALCULATE(",
              "        FIRSTNONBLANK(violations[violation_type], 1),",
              "        violations[object_name] = _name,",
              "        violations[triplet_name] = _trip",
              "    ),",
              "    \"Clean\"",
              ")"
            ],
            "displayFolder": "Inventory"
          },

          {
            "name": "Object Count",
            "expression": "COUNTROWS(inventory)",
            "formatString": "#,0",
            "displayFolder": "Inventory"
          },

          {
            "name": "Test Coverage Pct",
            "expression": [
              "VAR _devCount = CALCULATE(COUNTROWS(inventory), inventory[exists_in_dev] = TRUE())",
              "VAR _testCount = CALCULATE(COUNTROWS(inventory), inventory[exists_in_test] = TRUE())",
              "RETURN DIVIDE(_testCount, _devCount) * 100"
            ],
            "formatString": "0\"%\"",
            "displayFolder": "Coverage"
          },

          {
            "name": "Prod Coverage Pct",
            "expression": [
              "VAR _devCount = CALCULATE(COUNTROWS(inventory), inventory[exists_in_dev] = TRUE())",
              "VAR _prodCount = CALCULATE(COUNTROWS(inventory), inventory[exists_in_prod] = TRUE())",
              "RETURN DIVIDE(_prodCount, _devCount) * 100"
            ],
            "formatString": "0\"%\"",
            "displayFolder": "Coverage"
          }

        ]
      }

    ],

    "relationships": [
      {
        "name": "violations-to-inventory",
        "fromTable": "violations",
        "fromColumn": "object_name",
        "toTable": "inventory",
        "toColumn": "object_name",
        "crossFilteringBehavior": "oneDirection"
      }
    ],

    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.0.0"
      }
    ]
  }
}
